services:
  - type: web
    name: extension-selenium-api
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: mkdir -p ~/.config/pip && cp pip.conf ~/.config/pip/pip.conf && pip install --upgrade pip && pip install --only-binary=:all: -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    runtime: python
    runtimeVersion: "3.11.9"
    envVars:
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        value: us-east-1
      - key: PATTERN_API_URL
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
